### ISSUE TITLE
Layout option for reviewers

### ISSUE THREAD

**Issue by EddyLB** [vtex-soft/texsupport.iospress-jnr#1]
Is there a way to produce a PDF easier to work with for a reviewer i.e. with line numbers and larger line spacing. If not, could you please provide such a `\documentclass` option ?

**Comment by mingiss** [comment]
Sorry for the late answer.

I'm not sure, the features you mentioned should go to the class options, but you can simply do it in the document preamble by following commands:

Line numbering:
\usepackage{lineno}
\linenumbers

Switching off numbering, currently present in the class:
\makeatletter
\let\numberlines@hook\relax

Increase line spacing:
\linespread{2}

Regards, Mindaugas.
